application: winebits
version: 1
runtime: python27
api_version: 1
threadsafe: true

env_variables:
  DEBUG: True
  GOOGLE: True

includes:
- cellar/PineSocks/WineCellar.yaml

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /truth/.* 
  script: truth.main.application

- url: /donk
  static_dir: cellar/CrimsonDisk

- url: /kitchen
  static_dir: kitchen/www

- url: /style
  static_dir: style

skip_files:
- ^cellar/PineSocks/.sencha/*
#- ^cellar/PineSocks/app/*
#- ^cellar/PineSocks/ext/*
- ^cellar/PineSocks/ext/.sencha/*
- ^cellar/PineSocks/ext/builds/*
- ^cellar/PineSocks/ext/docs/*
- ^cellar/PineSocks/ext/examples/*
- ^cellar/PineSocks/ext/welcome/*
- ^cellar/PineSocks/ext/packages/ext-locale
- ^cellar/PineSocks/ext/packages/ext-theme-access
- ^cellar/PineSocks/ext/packages/ext-theme-base
- ^cellar/PineSocks/ext/packages/ext-theme-classic
- ^cellar/PineSocks/ext/packages/ext-theme-classic-sandbox
- ^cellar/PineSocks/ext/packages/ext-theme-gray
- ^cellar/PineSocks/ext/packages/ext-theme-neutral
- ^cellar/PineSocks/ext/packages/ext-theme-neptune/.sencha
- ^cellar/PineSocks/ext/packages/ext-theme-neptune/build
- ^cellar/PineSocks/ext/packages/ext-theme-neptune/docs
- ^cellar/PineSocks/ext/packages/ext-theme-neptune/licenses
- ^cellar/PineSocks/ext/packages/ext-theme-neptune/overrides
- ^cellar/PineSocks/ext/packages/ext-theme-neptune/resources
- ^cellar/PineSocks/ext/packages/ext-theme-neptune/sass
- ^cellar/PineSocks/ext/packages/ext-theme-neptune/src
- ^cellar/PineSocks/overrides/*
- ^cellar/PineSocks/packages/*
- ^cellar/PineSocks/sass/*
- ^cellar/PineSocks/server/static/temp/*
- ^chef/*
- ^Vagrantfile



libraries:
- name: webapp2
  version: "2.5.2"
