application: winebits
version: 1
runtime: python27
api_version: 1
threadsafe: true

env_variables:
  DEBUG: True
  GOOGLE: True

includes:
- WineCellar/PineSocks/WineCellar.yaml

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /truth/.* 
  script: truth.main.application

- url: /style
  static_dir: style

#- url: .*
#  script: main.app

skip_files:
- ^WineCellar/PineSocks/.sencha/*
- ^WineCellar/PineSocks/app/*
- ^WineCellar/PineSocks/ext/*
- ^WineCellar/PineSocks/overrides/*
- ^WineCellar/PineSocks/packages/*
- ^WineCellar/PineSocks/sass/*
- ^WineCellar/PineSocks/server/static/temp/*
- ^WineTruth/chef/*
- ^WineTruth/Vagrantfile



libraries:
- name: webapp2
  version: "2.5.2"
