application: winebits
version: 1
runtime: python27
api_version: 1
threadsafe: true

env_variables:
  DEBUG: True
  GOOGLE: True

includes:
- cellar/SpruceHat/SpruceHat.yaml
- cellar/PineSocks/WineCellar.yaml

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /truth/.* 
  script: truth.main.application

- url: /style
  static_dir: style

#- url: .*
#  script: main.app

skip_files:
- ^cellar/PineSocks/.sencha/*
#- ^cellar/PineSocks/app/*
#- ^cellar/PineSocks/ext/*
- ^cellar/PineSocks/ext/.sencha/*
- ^cellar/PineSocks/ext/builds/*
- ^cellar/PineSocks/ext/docs/*
- ^cellar/PineSocks/ext/examples/*
- ^cellar/PineSocks/ext/welcome/*
- ^cellar/PineSocks/overrides/*
- ^cellar/PineSocks/packages/*
- ^cellar/PineSocks/sass/*
- ^cellar/PineSocks/server/static/temp/*
- ^chef/*
- ^Vagrantfile



libraries:
- name: webapp2
  version: "2.5.2"
