# coding=latin-1

types = [
    "Red",
    "White",
    "Rose",
    "Blend",
    "Fruit/Vegetable Wine",
    "Dessert Wine",
    "Sparkling Red",
    "Sparkling White",
    "Fortified Red",
    "Fortified White"]

fruits = [
    'Apple',
    'Apricot',
    'Banana',
    'Blackberry',
    'Blackcurrant',
    'Blueberry',
    'Cashew',
    'Carrot',
    'Cherry',
    'Chive',
    'Cloudberry',
    'Cranberry',
    'Crowberry',
    'Dandelion',
    'Durian',
    'Elderberry',
    'Feljoa',
    'Fig',
    'Goji',
    'Wolfberry',
    'Gooseberry',
    'Hibiscus',
    'Huckleberry',
    'Kiwi',
    'Lemon',
    'Lemongrass',
    'Loquat',
    'Lychee',
    'Meijiu',
    'Mahonia',
    'Mango',
    'Nance',
    'Palm',
    'Parsnip',
    'Passion Fruit',
    'Peach',
    'Pear',
    'Pineapple',
    'Potato', #isn't that just vodka?
    'Plum',
    'Purple Mangosteen',
    'Raspberry',
    'Redcurrant',
    'Rhubarb',
    'Rowan',
    'Persimmon',
    'Pineapple',
    'Pomegranate',
    'Quince',
    'Rose Hip',
    'Saskatoon Berry',
    'Sea-buckthorn',
    'Strawberry',
    'Sweetsop',
    'Sweet Onion',
    'Tomato',
    'Umeshu',
    'Watermelon',
    'Whitecurrant',
]

varietals = [
    'Airén',
    'Albariño',
    'Albalonga',
    'Aligoté',
    'Alvarinho',
    'Alicante Bouschet',
    'Aligoté'
    'Amarone',
    'Arneis',
    'Asti Spumante',
    'Auslese',
    'Auxerrois',
    'Banylus',
    'Barbaresco',
    'Barbera',
    'Bardolino',
    'Barolo',
    'Beaujolais',
    'Blanc de Blancs',
    'Blanc de Noirs',
    'Blaufrankisch',
    'Blush',
    'Boal or Bual',
    'Brachetto',
    'Brunelletto',
    'Brunello',
    'Brunello Di Montalcino'
    'Cabernet Franc',
    'Cabernet Sauvignon',
    'Cacchiano',
    'Calabrese',
    'Cardisco',
    'Carignane/Cariñena',
    'Carmenere',
    'Catawba',
    'Cava',
    'Cencibel',
    'Charbono',
    'Chambourcin',
    'Champagne',
    'Chardonnay',
    'Chasellas/Gutedel',
    'Châteauneuf-du-Pape',
    'Chenin Blanc',
    'Chianti',
    'Chiantino',
    'Chianti Classico',
    'Cinsault',
    'Claret',
    'Colombard (French Colombard)',
    'Constantia',
    'Cordisio',
    'Corinto Nero',
    'Cortese',
    'Corvina',
    'Counoise',
    'Dolcetto',
    'Dolcetto Precoce',
    'Dornfelder',
    'Duriff',
    'Eiswein',
    'Ehrenfelser',
    'Folle blanche',
    'Frascati',
    'French Colombard',
    'Fumé Blanc',
    'Gamay',
    'Gamay Beaujolais',
    'Gattinara',
    'Gewürztraminer',
    'Graciano',
    'Grappa',
    'Grenache/Garnacha',
    'Grenache Blanc',
    'Grüner Veltliner',
    'Guarnacciola',
    'Huxelrebe',
    'Ingannacane',
    'Ives Noir',
    'Jacquère'
    'Johannisberg Riesling',
    'Kerner',
    'Kir',
    'Klevner',
    'Lambrusco',
    'Lambrusco Mendoza',
    'Lemberger',
    'Liebfraumilch',
    'Lillano',
    'Madeira',
    'Maglioppa',
    'Malbec',
    'Malmsey',
    'Malvasia',
    'Marc',
    'Marechal Foch',
    'Marsala',
    'Marsanne',
    'Mead',
    'Melon de Bourgogne',
    'Meritage',
    'Merlot',
    'Molinara',
    'Montepulciano',
    'Morellino',
    'Morellone',
    'Moscato',
    'Mourvedre/Mataro',
    'Müller-Thurgau',
    'Müllerrebe',
    'Muscadelle',
    'Muscat',
    'Muscateller',
    'Nebbiolo',
    'Negrello',
    'Negretta',
    'Negromaro',
    'Nerello',
    'Nerello Campotu',
    'Nerino',
    'Niella',
    'Nielluccia',
    'Nielluccio',
    'Norton',
    'Odjaleshi',
    'Ortega',
    'Palomino',
    'Parellada',
    'Pedro Ximenez',
    'Petite Verdot',
    'Petite Sirah',
    'Pigniuolo Rosso',
    'Pignolo',
    'Pinot Auxerrois',
    'Pinot Blanc',
    'Pinot Grigio/Pinot Gris',
    'Pinot Meunier',
    'Pinot Noir',
    'Pinotage',
    'Plant Romain',
    'Port',
    'Primaticcio',
    'Primitivo',
    'Primaticcio',
    'Prugnolo',
    'Prugnolo Dolce',
    'Prugnolo Di Montepulciano',
    'Prugnolo Gentile',
    'Prugnolo Gentile Di Montepulciano',
    'Puttanella',
    'Quagliano',
    'Retsina',
    'Riesling',
    'Riminese',
    'Rosé',
    'Roussane',
    'Rondinella',
    'Rosso di Montalcino',
    'Roter Veltliner',
    'Roussane',
    'Ruländer',
    'Saint George',
    'San Gloveto',
    'San Zoveto',
    'Sancivetro',
    'Sangiovese',
    'Sangineto',
    'Sangiogheto',
    'Sangiovese Dal Cannello Lungo',
    'Sangiovese Di Lamole',
    'Sangiovese Di Romagna',
    'Sangiovese Dolce',
    'Sangiovese Gentile',
    'Sangiovese Grosso',
    'Sangiovese Nostrano',
    'Sangiovese Piccolo',
    'Sangiovese Toscano',
    'Sangioveto',
    'Sangioveto Dolce',
    'Sangioveto Grosso',
    'Sangioveto Montanino',
    'Sankt Laurent',
    'Sanvincetro',
    'Sanzoveto',
    'Saperavi',
    'Sauvignon Blanc',
    'Scheurebe',
    'Schwarzriesling',
    'Scuppernong',
    'Sémillon',
    'Sherry',
    'Siegerrebe',
    'Syrah/Shiraz',
    'Soave',
    'Sylvaner',
    'Tabernello',
    'Tempranillo',
    'Tignolo',
    'Tinto de Toro',
    'Tinta del Pais',
    'Tinto Fino',
    'Tipsa',
    'Tocai Friulano',
    'Tokay',
    'Touriga Nacional',
    'Toustain',
    'Traminer',
    'Trebbiano',
    'Tuccanese',
    'Ugni Blanc',
    'Uva Abruzzi',
    'Uva Tosca',
    'Uvetta',
    'Uva Brunella',
    'Uva Canina',
    'Valpolicella',
    'Verdicchio',
    'Vidal Blanc',
    'Vigna del Conte',
    'Vigna Maggio',
    'Viognier',
    'Viura',
    'Welschriesling',
    'Xarello',
    'Yuga',
    'Zweigelt',
]

wine_options = ["Blend"] + varietals + fruits
